# Generated by Django 4.0.3 on 2023-07-19 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hats_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hat',
            name='fabric',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
