# Generated by Django 4.0.3 on 2023-07-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0005_binvo_import_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='bin_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoe', to='shoes_rest.binvo'),
        ),
    ]
